### ISSUE TITLE
EFL 1.0 development tracker

### ISSUE THREAD

**Issue by fkelava** [peppy-enterprises/fahrenheit#35]
This issue tracks remaining discussion points and open tasks for the 1.0 release of the Fahrenheit EFL.

Fahrenheit EFL utilizes a single hook at ``FFX.exe+2798E0(char* path, uint open_flags)`` returning a pointer to a structure like:
```cs
struct s {
    HANDLE handle_os;  // CreateFileW et al.
    void*  handle_vbf; // opaque structure used to handle VBF seeking
}
```

The game selects whether to use Windows file I/O APIs or VBF seeking depending on which of these fields is filled. Hence
```cs
s->handle_vbf = 0;
s->handle_os  = CreateFileW(...)
```
allows us to dupe the game into loading anything from disk. 

This can be applied two ways:
- as a postfix hook, allowing the game to complete the VBF load process _then_ substituting an OS handle if needed
- as a prefix hook, allocating our own structure and filling it appropriately

of which the latter is more performant and preferable, _but_ it is not yet confirmed that this is safe.

Mods will declare files they want EFL'd in ``data/x`` and ``data/x2`` under their mod directory, i.e. ``fahrenheit/modules/{MOD_NAME}/data/{x|x2}`` relative to the game executable. 

The structure of this folder must match the VBF exactly or no substitution will take place. Conflicts between two mods modifying the same file are resolved in load order. EFL precomputes a table of all modded files at initialization time, i.e. no runtime lookups are performed and its state and behavior are consistent for a given set of modules and load order.

The following tasks remain:
- [ ] Test the prefix hook method
- [ ] Test the load-order resolution
- [ ] Test the performance of precomputing the modded file table
- [ ] Test the finished module with "VBF-less" gameplay and the Masters Challenge
- [ ] Find the equivalent method in X-2 and support it

**Comment by fkelava** [comment]
The issue has been transferred here as a result of 10795c4, which made the EFL a component of the Fahrenheit runtime.

**Comment by EvelynTSMG** [comment]
As noted by Piko [here](https://discord.com/channels/1328407223528853598/1328428782863913043/1351722472105574443), the game contains a file which dictates the sizes of some files which the game loads.
We need to:
- [ ] Make sure the issue encountered is reproducable
- [ ] Fix the issue if it is
I suggest hooking wherever the game gets the size and providing our own live instead of something like manually building the file and providing it ourselves to allow for future hot(-ish) reload of some files.

**Comment by fkelava** [comment]
The implementation of the EFL implicitly permits hot reload of files as long as they are not modified while the game is actively issuing I/O against them.
